/**
 * ============================================================================
 * SkyGuard AI - Tier 1: The Station Edge Engine
 * Core ESP32 / ARM Cortex-M4 Embedded C++ Header Prototype
 * File: firmware_esp32_core.h
 * 
 * Hardware Profile:
 *   - Target Architecture: Xtensa Dual-Core 32-bit LX6 (ESP32) / ARM Cortex-M4
 *   - Operating Constraints: <= 30 KB SRAM allocation budget (zero heap allocation)
 *   - Compute Budget: < 10 ms per observation cycle at 160 MHz
 *   - Telemetry: MQTT QoS 1 with local circular SPIFFS/Flash spool fallback
 * ============================================================================
 */

#ifndef FIRMWARE_ESP32_CORE_H
#define FIRMWARE_ESP32_CORE_H

#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <stdio.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * 1. CONFIGURATION CONSTANTS & BITMASKS
 * ============================================================================ */

// Static Boundary Limits
#define EDGE_TEMP_MIN_C           (-20.0f)
#define EDGE_TEMP_MAX_C           (60.0f)
#define EDGE_PRESS_MIN_HPA        (800.0f)
#define EDGE_PRESS_MAX_HPA        (1100.0f)
#define EDGE_HUMID_MIN_PCT        (0.0f)
#define EDGE_HUMID_MAX_PCT        (100.0f)

// ADC Rail / Disconnect Detection Thresholds
#define EDGE_ADC_DISCONNECT_TEMP  (-990.0f)
#define EDGE_ADC_CORRUPT_HUMID    (105.0f)

// Temporal Invariant Thresholds (per 5-min tick)
#define EDGE_SPIKE_DELTA_T_MAX    (8.0f)    // deg C
#define EDGE_SPIKE_DELTA_P_MAX    (6.0f)    // hPa
#define EDGE_SPIKE_DELTA_RH_MAX   (30.0f)   // %
#define EDGE_FROZEN_VARIANCE_MIN  (1e-5f)   // Variance threshold for flatline

// Psychrometric Check Constants
#define MAGNUS_A                  (17.67f)
#define MAGNUS_B                  (243.5f)
#define MAGNUS_C                  (6.112f)
#define SUPERSAT_THRESHOLD_C      (0.5f)

// System Ring & Spool Buffer Capacities
#define EDGE_RING_BUFFER_SIZE     (12)      // W = 12 samples (1 hour at 5-min cadence)
#define EDGE_MAX_SPOOL_RECORDS    (64)      // Flash/SPIFFS spool queue capacity
#define EDGE_MAX_PAYLOAD_SIZE     (280)     // Maximum JSON payload string length

// Local Edge Flag Bitmask
#define EDGE_PASS                         (0x00)
#define EDGE_ERR_OUT_OF_BOUNDS            (0x01)
#define EDGE_ERR_THERMODYNAMIC_IMPOSSIBLE (0x02)
#define EDGE_SUSPECT_STEP_SPIKE           (0x04)
#define EDGE_ERR_SENSOR_FROZEN            (0x08)
#define EDGE_ERR_TELEMETRY_CORRUPT        (0x10)

/* ============================================================================
 * 2. TYPE DEFINITIONS & DATA STRUCTURES
 * ============================================================================ */

/**
 * Raw physical sensor reading collected from hardware bus (I2C/SPI/ADC).
 * Size: 16 bytes.
 */
typedef struct {
    float T;                    // Temperature in deg C
    float P;                    // Atmospheric pressure in hPa
    float RH;                   // Relative humidity in %
    uint32_t timestamp_epoch;   // Unix epoch seconds
} SensorRawReading;

/**
 * Edge analysis result generated by micro-screener.
 * Size: 52 bytes.
 */
typedef struct {
    uint8_t flag;               // Bitmask of flags
    char desc[32];              // Descriptive summary string
    float td;                   // Computed dew point (deg C)
    float t_step;               // Step difference delta T
    float p_step;               // Step difference delta P
    float rh_step;              // Step difference delta RH
} EdgeAnalysisResult;

/**
 * Diagnostics & Power metadata.
 * Size: 8 bytes.
 */
typedef struct {
    float vbat;                 // Battery voltage (e.g. 3.82V)
    int16_t rssi;               // Cellular/LoRa RSSI (e.g. -74 dBm)
    uint16_t spool_len;         // Number of records currently spooled
} EdgeDiagInfo;

/**
 * Static circular ring buffer for micro-temporal history (W=12).
 * Zero heap allocation.
 * Footprint: 12 * 16 + 8 = 200 bytes.
 */
typedef struct {
    SensorRawReading buffer[EDGE_RING_BUFFER_SIZE];
    uint8_t head;
    uint8_t count;
} StaticRingBuffer;

/**
 * Compact Spool Record for offline circular flash storage.
 * Footprint: EDGE_MAX_SPOOL_RECORDS * 280 bytes = ~17.9 KB.
 * Strictly within <= 30 KB SRAM budget.
 */
typedef struct {
    char payload[EDGE_MAX_PAYLOAD_SIZE];
} SpoolRecord;

typedef struct {
    SpoolRecord queue[EDGE_MAX_SPOOL_RECORDS];
    uint16_t head;
    uint16_t tail;
    uint16_t count;
    uint32_t total_dropped_overflow;
} CircularSpoolStorage;

/* ============================================================================
 * 3. RING BUFFER UTILITIES (Zero Heap Allocation)
 * ============================================================================ */

static inline void ring_buffer_init(StaticRingBuffer* rb) {
    if (!rb) return;
    rb->head = 0;
    rb->count = 0;
    memset(rb->buffer, 0, sizeof(rb->buffer));
}

static inline void ring_buffer_push(StaticRingBuffer* rb, const SensorRawReading* sample) {
    if (!rb || !sample) return;
    rb->buffer[rb->head] = *sample;
    rb->head = (uint8_t)((rb->head + 1) % EDGE_RING_BUFFER_SIZE);
    if (rb->count < EDGE_RING_BUFFER_SIZE) {
        rb->count++;
    }
}

static inline const SensorRawReading* ring_buffer_get_latest(const StaticRingBuffer* rb) {
    if (!rb || rb->count == 0) return NULL;
    uint8_t idx = (uint8_t)((rb->head + EDGE_RING_BUFFER_SIZE - 1) % EDGE_RING_BUFFER_SIZE);
    return &rb->buffer[idx];
}

/* ============================================================================
 * 4. EDGE PROCESSING SCREENER MODULES
 * ============================================================================ */

/**
 * Module A: Static Boundaries & ADC Corruption Filter (< 0.1 ms)
 * Flags NaN, Inf, disconnected ADC rail pulls, or out-of-physical range data.
 */
static inline uint8_t edge_check_static_bounds(const SensorRawReading* r) {
    if (!r) return EDGE_ERR_TELEMETRY_CORRUPT;

    // Check for NaN or Inf (bit-flips, I2C/SPI bus read corruptions)
    if (isnan(r->T) || isnan(r->P) || isnan(r->RH) ||
        isinf(r->T) || isinf(r->P) || isinf(r->RH)) {
        return (EDGE_ERR_OUT_OF_BOUNDS | EDGE_ERR_TELEMETRY_CORRUPT);
    }

    // Check for disconnected ADC rail pulls (-999.0C) or hardware saturation (>105% RH)
    if (r->T <= EDGE_ADC_DISCONNECT_TEMP || r->RH > EDGE_ADC_CORRUPT_HUMID || r->RH < -5.0f) {
        return EDGE_ERR_OUT_OF_BOUNDS;
    }

    // Check physical operational bounds
    if (r->T < EDGE_TEMP_MIN_C || r->T > EDGE_TEMP_MAX_C ||
        r->P < EDGE_PRESS_MIN_HPA || r->P > EDGE_PRESS_MAX_HPA ||
        r->RH < EDGE_HUMID_MIN_PCT || r->RH > EDGE_HUMID_MAX_PCT) {
        return EDGE_ERR_OUT_OF_BOUNDS;
    }

    return EDGE_PASS;
}

/**
 * Module B: Fast Fixed-Point / Integer-Safe Thermodynamic Invariant Check (< 1.0 ms)
 * Uses August-Roche-Magnus approximation to compute saturation vapor pressure e_s(T),
 * actual vapor pressure e, and dew point T_d.
 * Edge Invariant Rules:
 *   1. Violation if T_d > T + 0.5 C (supersaturation beyond physical threshold)
 *   2. Violation if T > 40 C and RH > 90% simultaneously without barometric depression (P >= 1000 hPa).
 */
static inline uint8_t edge_check_thermodynamic_invariants(const SensorRawReading* r, float* out_td) {
    if (!r || !out_td) return EDGE_ERR_TELEMETRY_CORRUPT;

    *out_td = -999.0f; // Default uncalculated

    // Guard against calculation if values are wildly out of bounds
    if (isnan(r->T) || isnan(r->RH) || r->RH <= 0.0f || r->T < -80.0f || r->T > 100.0f) {
        return EDGE_ERR_THERMODYNAMIC_IMPOSSIBLE;
    }

    // 1. Saturation vapor pressure: e_s(T) = 6.112 * exp((17.67 * T) / (T + 243.5))
    float t_denom = r->T + MAGNUS_B;
    if (fabsf(t_denom) < 1e-4f) return EDGE_ERR_THERMODYNAMIC_IMPOSSIBLE;

    float es = MAGNUS_C * expf((MAGNUS_A * r->T) / t_denom);

    // 2. Actual vapor pressure: e = e_s * (RH / 100.0)
    float rh_clamped = (r->RH > 100.0f) ? 100.0f : ((r->RH < 0.01f) ? 0.01f : r->RH);
    float e = es * (rh_clamped / 100.0f);

    // 3. Dew Point: T_d = (243.5 * ln(e / 6.112)) / (17.67 - ln(e / 6.112))
    float log_val = logf(e / MAGNUS_C);
    float denom = MAGNUS_A - log_val;
    if (fabsf(denom) < 1e-4f) return EDGE_ERR_THERMODYNAMIC_IMPOSSIBLE;

    float td = (MAGNUS_B * log_val) / denom;
    *out_td = td;

    uint8_t flag = EDGE_PASS;

    // Rule 1: Supersaturation check
    if (td > (r->T + SUPERSAT_THRESHOLD_C)) {
        flag |= EDGE_ERR_THERMODYNAMIC_IMPOSSIBLE;
    }

    // Rule 2: Extreme heat + humidity without severe barometric depression
    if (r->T > 40.0f && r->RH > 90.0f && r->P >= 1000.0f) {
        flag |= EDGE_ERR_THERMODYNAMIC_IMPOSSIBLE;
    }

    return flag;
}

/**
 * Module C: Micro-Temporal Ring Buffer Analysis (< 2.0 ms)
 * Evaluates step jumps and deadband / flatline variance over the last W=12 readings.
 */
static inline uint8_t edge_check_temporal_invariants(
    const SensorRawReading* r,
    const StaticRingBuffer* rb,
    float* out_t_step,
    float* out_p_step,
    float* out_rh_step
) {
    if (!r || !rb || !out_t_step || !out_p_step || !out_rh_step) {
        return EDGE_ERR_TELEMETRY_CORRUPT;
    }

    uint8_t flag = EDGE_PASS;
    *out_t_step = 0.0f;
    *out_p_step = 0.0f;
    *out_rh_step = 0.0f;

    // Step change check against previous reading
    const SensorRawReading* prev = ring_buffer_get_latest(rb);
    if (prev != NULL) {
        *out_t_step = r->T - prev->T;
        *out_p_step = r->P - prev->P;
        *out_rh_step = r->RH - prev->RH;

        if (fabsf(*out_t_step) > EDGE_SPIKE_DELTA_T_MAX ||
            fabsf(*out_p_step) > EDGE_SPIKE_DELTA_P_MAX ||
            fabsf(*out_rh_step) > EDGE_SPIKE_DELTA_RH_MAX) {
            flag |= EDGE_SUSPECT_STEP_SPIKE;
        }
    }

    // Deadband / Flatline check: Calculate variance over full window W=12
    if (rb->count >= EDGE_RING_BUFFER_SIZE) {
        float sum_t = 0.0f, sum_p = 0.0f, sum_rh = 0.0f;
        for (uint8_t i = 0; i < EDGE_RING_BUFFER_SIZE; ++i) {
            sum_t += rb->buffer[i].T;
            sum_p += rb->buffer[i].P;
            sum_rh += rb->buffer[i].RH;
        }
        float mean_t = sum_t / (float)EDGE_RING_BUFFER_SIZE;
        float mean_p = sum_p / (float)EDGE_RING_BUFFER_SIZE;
        float mean_rh = sum_rh / (float)EDGE_RING_BUFFER_SIZE;

        float var_t = 0.0f, var_p = 0.0f, var_rh = 0.0f;
        for (uint8_t i = 0; i < EDGE_RING_BUFFER_SIZE; ++i) {
            float dt = rb->buffer[i].T - mean_t;
            float dp = rb->buffer[i].P - mean_p;
            float drh = rb->buffer[i].RH - mean_rh;
            var_t += dt * dt;
            var_p += dp * dp;
            var_rh += drh * drh;
        }
        var_t /= (float)EDGE_RING_BUFFER_SIZE;
        var_p /= (float)EDGE_RING_BUFFER_SIZE;
        var_rh /= (float)EDGE_RING_BUFFER_SIZE;

        // If variance <= 1e-5 on any channel, sensor is frozen
        if (var_t <= EDGE_FROZEN_VARIANCE_MIN ||
            var_p <= EDGE_FROZEN_VARIANCE_MIN ||
            var_rh <= EDGE_FROZEN_VARIANCE_MIN) {
            flag |= EDGE_ERR_SENSOR_FROZEN;
        }
    }

    return flag;
}

/**
 * Generates descriptive status string for the bitmask flag.
 */
static inline void edge_flag_to_desc(uint8_t flag, char* desc_buf, size_t buf_len) {
    if (!desc_buf || buf_len == 0) return;

    if (flag == EDGE_PASS) {
        strncpy(desc_buf, "EDGE_PASS", buf_len - 1);
        desc_buf[buf_len - 1] = '\0';
        return;
    }

    desc_buf[0] = '\0';
    bool first = true;

    if (flag & EDGE_ERR_OUT_OF_BOUNDS) {
        strncat(desc_buf, "EDGE_ERR_OUT_OF_BOUNDS", buf_len - strlen(desc_buf) - 1);
        first = false;
    }
    if (flag & EDGE_ERR_THERMODYNAMIC_IMPOSSIBLE) {
        if (!first) strncat(desc_buf, "|", buf_len - strlen(desc_buf) - 1);
        strncat(desc_buf, "EDGE_ERR_THERMODYNAMIC_IMPOSSIBLE", buf_len - strlen(desc_buf) - 1);
        first = false;
    }
    if (flag & EDGE_SUSPECT_STEP_SPIKE) {
        if (!first) strncat(desc_buf, "|", buf_len - strlen(desc_buf) - 1);
        strncat(desc_buf, "EDGE_SUSPECT_STEP_SPIKE", buf_len - strlen(desc_buf) - 1);
        first = false;
    }
    if (flag & EDGE_ERR_SENSOR_FROZEN) {
        if (!first) strncat(desc_buf, "|", buf_len - strlen(desc_buf) - 1);
        strncat(desc_buf, "EDGE_ERR_SENSOR_FROZEN", buf_len - strlen(desc_buf) - 1);
        first = false;
    }
    if (flag & EDGE_ERR_TELEMETRY_CORRUPT) {
        if (!first) strncat(desc_buf, "|", buf_len - strlen(desc_buf) - 1);
        strncat(desc_buf, "EDGE_ERR_TELEMETRY_CORRUPT", buf_len - strlen(desc_buf) - 1);
    }
}

/**
 * Master Edge Engine Screener Pipeline: Runs Module A, B, and C sequentially.
 * Execution Time: < 3.1 ms on Xtensa 160 MHz.
 */
static inline EdgeAnalysisResult edge_process_observation(
    const SensorRawReading* r,
    StaticRingBuffer* rb
) {
    EdgeAnalysisResult res;
    memset(&res, 0, sizeof(res));

    if (!r) {
        res.flag = EDGE_ERR_TELEMETRY_CORRUPT;
        edge_flag_to_desc(res.flag, res.desc, sizeof(res.desc));
        return res;
    }

    // Module A: Static Bounds & ADC Corruption
    uint8_t flag_a = edge_check_static_bounds(r);

    // Module B: Thermodynamic Invariants (August-Roche-Magnus)
    float td = 0.0f;
    uint8_t flag_b = edge_check_thermodynamic_invariants(r, &td);
    res.td = td;

    // Module C: Micro-Temporal Ring Buffer Analysis
    float t_step = 0.0f, p_step = 0.0f, rh_step = 0.0f;
    uint8_t flag_c = edge_check_temporal_invariants(r, rb, &t_step, &p_step, &rh_step);
    res.t_step = t_step;
    res.p_step = p_step;
    res.rh_step = rh_step;

    // Aggregate bitmask
    res.flag = flag_a | flag_b | flag_c;
    edge_flag_to_desc(res.flag, res.desc, sizeof(res.desc));

    // Update ring buffer with current reading (only if numeric)
    if (!isnan(r->T) && !isnan(r->P) && !isnan(r->RH)) {
        ring_buffer_push(rb, r);
    }

    return res;
}

/* ============================================================================
 * 5. TELEMETRY SERIALIZATION & RESILIENT FLASH SPOOL ENGINE
 * ============================================================================ */

/**
 * Formats compact MQTT JSON telemetry payload according to SkyGuard Edge Schema.
 * Uses stack-safe snprintf with zero heap allocation.
 */
static inline int edge_serialize_json_payload(
    const char* station_id,
    const char* timestamp_iso,
    const SensorRawReading* r,
    const EdgeAnalysisResult* edge,
    const EdgeDiagInfo* diag,
    char* out_buf,
    size_t max_buf_len
) {
    if (!station_id || !timestamp_iso || !r || !edge || !diag || !out_buf || max_buf_len == 0) {
        return -1;
    }

    return snprintf(
        out_buf,
        max_buf_len,
        "{\"sid\":\"%s\",\"ts\":\"%s\",\"raw\":{\"T\":%.2f,\"P\":%.2f,\"RH\":%.2f},\"edge\":{\"flag\":%u,\"desc\":\"%s\",\"td\":%.2f,\"t_step\":%.2f,\"p_step\":%.2f,\"rh_step\":%.2f},\"diag\":{\"vbat\":%.2f,\"rssi\":%d,\"spool_len\":%u}}",
        station_id,
        timestamp_iso,
        r->T,
        r->P,
        r->RH,
        (unsigned int)edge->flag,
        edge->desc,
        edge->td,
        edge->t_step,
        edge->p_step,
        edge->rh_step,
        diag->vbat,
        (int)diag->rssi,
        (unsigned int)diag->spool_len
    );
}

/**
 * Circular Spool Storage: Flash/SPIFFS persistent storage simulation.
 */
static inline void spool_storage_init(CircularSpoolStorage* spool) {
    if (!spool) return;
    spool->head = 0;
    spool->tail = 0;
    spool->count = 0;
    spool->total_dropped_overflow = 0;
    memset(spool->queue, 0, sizeof(spool->queue));
}

/**
 * Enqueue payload during network blackout.
 * Overwrites oldest if capacity reached to preserve the most recent telemetry.
 */
static inline bool spool_storage_push(CircularSpoolStorage* spool, const char* json_payload) {
    if (!spool || !json_payload) return false;

    if (spool->count >= EDGE_MAX_SPOOL_RECORDS) {
        // Queue full: overwrite oldest (circular FIFO drop)
        spool->tail = (spool->tail + 1) % EDGE_MAX_SPOOL_RECORDS;
        spool->total_dropped_overflow++;
    } else {
        spool->count++;
    }

    strncpy(spool->queue[spool->head].payload, json_payload, EDGE_MAX_PAYLOAD_SIZE - 1);
    spool->queue[spool->head].payload[EDGE_MAX_PAYLOAD_SIZE - 1] = '\0';
    spool->head = (spool->head + 1) % EDGE_MAX_SPOOL_RECORDS;

    return true;
}

/**
 * Pop oldest payload when network reconnects (FIFO drain).
 */
static inline bool spool_storage_pop(CircularSpoolStorage* spool, char* out_payload, size_t max_len) {
    if (!spool || !out_payload || spool->count == 0) return false;

    strncpy(out_payload, spool->queue[spool->tail].payload, max_len - 1);
    out_payload[max_len - 1] = '\0';

    spool->tail = (spool->tail + 1) % EDGE_MAX_SPOOL_RECORDS;
    spool->count--;

    return true;
}

static inline uint16_t spool_storage_get_count(const CircularSpoolStorage* spool) {
    return spool ? spool->count : 0;
}

#ifdef __cplusplus
}
#endif

#endif // FIRMWARE_ESP32_CORE_H
